steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/predictionpro-io/cloud-run-source-deploy/hackathon-oracle-api:$COMMIT_SHA'
      - '.'

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/predictionpro-io/cloud-run-source-deploy/hackathon-oracle-api:$COMMIT_SHA'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'hackathon-oracle-api'
      - '--image=europe-west1-docker.pkg.dev/predictionpro-io/cloud-run-source-deploy/hackathon-oracle-api:$COMMIT_SHA'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'

images:
  - 'europe-west1-docker.pkg.dev/predictionpro-io/cloud-run-source-deploy/hackathon-oracle-api:$COMMIT_SHA'